------ DAY- 2 OF SQL LEARNING -----


--------- Level 3: Aggregate Functions (Extremely Important) ------

SELECT COUNT(*) FROM AGENTS 
 SELECT MAX(COMMISSION) FROM AGENTS AS max_commission
SELECT  MIN(COMMISSION) FROM AGENTS AS min_commission
SELECT AVG(COMMISSION) FROM AGENTS AS avg_commission
SELECT SUM(COMMISSION) FROM AGENTS AS total_commission 
SELECT COUNT(*) FROM AGENTS WHERE WORKING_AREA LIKE 'BANGALORE' 

------- Level 4: GROUP BY (One of the Most Important) -------

SELECT COUNT(AGENT_CODE) AS total_agents FROM AGENTS
GROUP BY 
    WORKING_AREA
ORDER BY 
    total_agents DESC;

SELECT AVG(COMMISSION) AS avg_agents FROM AGENTS GROUP BY WORKING_AREA ORDER BY avg_agents DESC
SELECT WORKING_AREA, MAX(COMMISSION) AS max_commission FROM AGENTS GROUP BY WORKING_AREA ORDER BY max_commission DESC
SELECT WORKING_AREA, MIN(COMMISSION) AS min_commission FROM AGENTS GROUP BY WORKING_AREA ORDER BY min_commission DESC
SELECT WORKING_AREA, COUNT(COMMISSION) AS count_commission FROM AGENTS GROUP BY WORKING_AREA ORDER BY count_commission DESC

