------ DAY- 3 OF SQL LEARNING -----


-------  Level 5: HAVING (Important) ------------

SELECT WORKING_AREA FROM AGENTS GROUP BY WORKING_AREA HAVING COUNT(*) > 1;
SELECT WORKING_AREA FROM AGENTS GROUP BY WORKING_AREA HAVING AVG(COMMISSION) > 0.13 ;
SELECT WORKING_AREA AS CITY , COUNT(COMMISSION) AS total_commission
FROM AGENTS 
GROUP BY WORKING_AREA
HAVING COUNT(COMMISSION);

------- Level 6: String Functions -----

SELECT 
UPPER(AGENT_NAME) AS agents_name 
FROM AGENTS

SELECT 
LOWER(AGENT_NAME) AS agents_name 
FROM AGENTS

SELECT 
LENGTH(AGENT_NAME) AS agents_name 
FROM AGENTS

SELECT LEFT(AGENT_NAME, 3) AS agents_name 
FROM AGENTS

SELECT REPLACE(AGENT_NAME,  'a', '*') AS replaced_coloum 
FROM AGENTS