------ DAY- 1 OF SQL LEARNING -----

--------- Level 1: SELECT, WHERE (Most Used) ------

SELECT * FROM AGENTS;
SELECT AGENT_NAME, WORKING_AREA FROM AGENTS;
SELECT * FROM AGENTS WHERE WORKING_AREA LIKE '%LONDON%'
SELECT * FROM AGENTS WHERE COMMISSION > '0.14';
 SELECT * FROM AGENTS WHERE COMMISSION BETWEEN '0.12' AND '0.15'
SELECT * FROM AGENTS WHERE WORKING_AREA IN ('LONDON', 'BANGALORE');
 SELECT * FROM AGENTS WHERE COUNTRY IS NULL
SELECT * FROM AGENTS
SELECT * FROM AGENTS WHERE AGENT_NAME LIKE 'A%'
SELECT * FROM AGENTS WHERE AGENT_NAME LIKE '%n'
SELECT * FROM AGENTS WHERE AGENT_NAME LIKE '_u%'

--------  Level 2: ORDER BY & LIMIT (Very Common) -------

SELECT * FROM AGENTS ORDER BY COMMISSION ASC
 SELECT * FROM AGENTS ORDER BY AGENT_NAME ASC
 SELECT * FROM AGENTS ORDER BY COMMISSION DESC LIMIT 3;
SELECT * FROM AGENTS ORDER BY COMMISSION ASC LIMIT 1


------ DAY- 2 OF SQL LEARNING -----

